Domain:
    clients: ['http://localhost:4200']

DatabaseModule:
    prefix: database
    swagger:
        title: DatabaseModule
        description: Provides database
        path: database-module

AuthModule:
    prefix: auth
    active: false
    swagger:
        title: AuthModule
        description: Provides authentication and authorization services
        path: auth-module

MessageModule:
    prefix: message
