Domain:
    clients: ['http://localhost:4200']
DatabaseModule:
    swagger:
        title: DatabaseModule
        description: Provides database services
        path: database-module
    connection:
        type: postgres
        appname: authdare
        database: authdare
        # database: database/authdare/main.sqlite
        username: postgres
        password: password
        synchronize: true
        dropSchema: true

AuthModule:
    swagger:
        title: AuthModule
        description: Provides authentication and authorization services
        path: auth-module
    jwt:
        secret: 'secret'
        expirations:
            admin: 30 day
            client: 3 months
