name: Global Configuration
database:
    swagger:
        title: Database Module
        description: Provides database services
        path: dba

    connection:
        type: postgres
        database: authdare
        # database: database/authdare/main.sqlite
        username: postgres
        password: password
        synchronize: true
        dropSchema: true

auth:
    swagger:
        title: Auth Module
        description: Provides authentication and authorization services
        path: auth

    jwt:
        secret: 'secret'
        expirations:
            admin: 30 day
            client: 3 months
