# Use this connection to create databases
database:
    initial:
        name: initial
        type: postgres
        database: postgres
        username: postgres
        password: password
        keepConnectionAlive: false
        databases: ['config', 'config_1', 'config_2']

    # main database configuraiton
    main:
        type: postgres
        logging: true
        entities: ['users', 'logs']
        replication:
            master:
                name: main
                database: config
                username: postgres
                password: password
                synchronize: true
                dropSchema: true
            slaves:
                - database: config_1
                  username: postgres
                  password: password
                  synchronize: true
                  dropSchema: true
                - database: config_2
                  username: postgres
                  password: password
                  synchronize: true
                  dropSchema: true
    #
    #
    #
